# Auto-generated from "Team Data - Closer Details.xlsx" — engineer full names and their team lead.
# (full_name, team_lead_name)

ENGINEERS: list[tuple[str, str | None]] = [
    ('Muhammad Mahroz Khan', 'Muneeb Awais Sheikh'),
    ('Arslan Asif', 'Muhammad Mahroz Khan'),
    ('Aiza Ihsan', 'Arslan Asif'),
    ('Muhammad Saim Malik', 'Arslan Asif'),
    ('Umair Dar', 'Arslan Asif'),
    ('Muhammad Wasil Shahzad', 'Arslan Asif'),
    ('Khadija Zahid', 'Abdul Wahab Mirza'),
    ('Abdul Wahab Mirza', 'Muhammad Mahroz Khan'),
    ('Ahmed Azhar', 'Arslan Asif'),
    ('Alishba Saeed', 'Muhammad Faizan Azhar'),
    ('Talal Zulfiqar', 'Muhammad Faizan Azhar'),
    ('Muhammad Ibrahim', 'Arslan Asif'),
    ('Faizan Ul Haq', 'Arslan Asif'),
    ('Amna Khalid', 'Muhammad Faizan Azhar'),
    ('Mohammad Asadullah Siddiqui', 'Arslan Asif'),
    ('Kashif Mehmood', 'Arslan Asif'),
    ('Muhammad Qasim Yousaf', 'Arslan Asif'),
    ('Muhammad Faizan Azhar', 'Muhammad Mahroz Khan'),
    ('Muhammad Ikram Ali', 'Muhammad Faizan Azhar'),
    ('Fatima Muneer', 'Muhammad Faizan Azhar'),
    ('Syed Hamza Ali', 'Muhammad Faizan Azhar'),
    ('Shaheer Bin Ijaz', 'Muhammad Faizan Azhar'),
    ('Muhammad Faizan Qadri', 'Alishba Saeed'),
    ('Wardah Arshad', 'Abdul Wahab Mirza'),
    ('Sidra Mushtaq', 'Abdul Wahab Mirza'),
    ('Musa Umer', 'Abdul Wahab Mirza'),
    ('Muhammad Hammad Rashid', 'Abdul Wahab Mirza'),
    ('Javeria Tariq', 'Abdul Wahab Mirza'),
    ('Muhammad Sami Khokher', 'Muhammad Saim Malik'),
    ('Muhammad Umar', 'Arslan Asif'),
    ('Shayan Mukhtar', 'Arslan Asif'),
    ('Zia Ur Rehman', 'Arslan Asif'),
    ('Abubakr Idrees Bhutta', 'Arslan Asif'),
    ('Raja Mohsin Tariq', 'Arslan Asif'),
    ('Umer Waheed', 'Arslan Asif'),
    ('Samreen Riaz', 'Arslan Asif'),
    ('Abdullah Khan', 'Muhammad Faizan Azhar'),
    ('Muhammad Yahya', 'Muhammad Faizan Azhar'),
    ('Mohid Subhani', 'Arslan Asif'),
    ('Ch Waleed Ishtiaq', 'Arslan Asif'),
    ('Shais Ur Rehman', 'Arslan Asif'),
    ('Abdul Mateen', 'Arslan Asif'),
    ('Muhammad Musharraf Tahir', 'Arslan Asif'),
    ('Muhammad Ibrahim Raza', 'Muhammad Saim Malik'),
    ('Syed Abbas Rizvi', 'Arslan Asif'),
    ('Sahibzada Syed Ali Gillani', 'Muhammad Saim Malik'),
    ('Muhammad Usman Ali', 'Muhammad Saim Malik'),
    ('Ahmad Hassaan', 'Muhammad Mahroz Khan'),
    ('Usama Tariq', 'Muhammad Mahroz Khan'),
    ('Jasim Imran', 'Muhammad Mahroz Khan'),
    ('Hira Waheed', 'Arslan Asif'),
    ('Muhammad Jawad Amin', 'Arslan Asif'),
    ('Numair Imtiaz Cheema', 'Arslan Asif'),
    ('Muhammad Abdullah', 'Arslan Asif'),
    ('Maryam Saqib', 'Arslan Asif'),
    ('Saboor Ahmed', 'Arslan Asif'),
    ('Muhammad Muaaz Aamer', 'Arslan Asif'),
    ('Moeiz Shahzad', 'Arslan Asif'),
    ('Husnain Siddique', 'Muhammad Faizan Azhar'),
    ('Muhammad Usman Latif', 'Muhammad Faizan Azhar'),
    ('Asad Rehman', 'Muhammad Faizan Azhar'),
    ('Anas Waleed Tahir', 'Muhammad Faizan Azhar'),
    ('Saad Asif', 'Muhammad Faizan Azhar'),
    ('Saram Khalil', 'Muhammad Saim Malik'),
    ('Anjum Hussain', 'Khadija Zahid'),
    ('Kainnat Batool', 'Khadija Zahid'),
    ('Muhammad Usman', 'Arslan Asif'),
    ('Muhammad Ayan', 'Arslan Asif'),
    ('Asad Tariq', 'Arslan Asif'),
    ('Muhammad Usama', 'Arslan Asif'),
    ('Saif Ullah Arshad', 'Muhammad Faizan Azhar'),
    ('Hassan Abdul Jabbar', 'Arslan Asif'),
    ('Muhammad Sher Afgan Bhatti', 'Arslan Asif'),
    ('Saman Rafiq', 'Arslan Asif'),
    ('Fiza Shahzad', 'Arslan Asif'),
    ('Laila Khan', 'Arslan Asif'),
    ('Hamza Naeem', 'Arslan Asif'),
    ('Mehak', 'Alishba Saeed'),
    ('Maheen Butt', 'Alishba Saeed'),
    ('Muhammad Rafay Ul Haq', 'Muhammad Saim Malik'),
    ('Muhammad Moazzam Anwaar', 'Arslan Asif'),
    ('Omar Tehzeeb', 'Muhammad Mahroz Khan'),
    ('Bilal Nadeem', 'Abdul Wahab Mirza'),
    ('Waleed Naeem', 'Arslan Asif'),
]
